services:
  slashviberepo:
    build: .
    image: ghcr.io/its-the-vibe/slashviberepo:latest
    pull_policy: always
    read_only: true
    volumes:
      - ./config.json:/config.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CONFIG_FILE=/config.json
      - REDIS_ADDR=${REDIS_ADDR:-host.docker.internal:6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CHANNEL=${REDIS_CHANNEL:-slack-commands}
      - REDIS_VIEW_SUBMISSION_CHANNEL=${REDIS_VIEW_SUBMISSION_CHANNEL:-slack-relay-view-submission}
      - REDIS_POPPIT_LIST=${REDIS_POPPIT_LIST:-poppit:notifications}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - GITHUB_ORG=${GITHUB_ORG}
      - WORKING_DIR=${WORKING_DIR:-/tmp}
      - VIBEOPS_WORKING_DIR=${VIBEOPS_WORKING_DIR}
      - GITHUB_PRIVATE_WORKING_DIR=${GITHUB_PRIVATE_WORKING_DIR}
    restart: on-failure:10
